/*
 * motors_driver.c
 *
 *  Created on: Jan 29, 2024
 *      Author: root
 */

#include "motors_driver.h"


void startTurningRight(){
  	HAL_GPIO_WritePin(STEP_MOTOR1_BASE, STEP_MOTOR1_PIN, GPIO_PIN_SET);
  	HAL_GPIO_WritePin(STEP_MOTOR2_BASE, STEP_MOTOR2_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR3_BASE, STEP_MOTOR3_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR4_BASE, STEP_MOTOR4_PIN, GPIO_PIN_RESET);
  	osDelay(2);

  	HAL_GPIO_WritePin(STEP_MOTOR1_BASE, STEP_MOTOR1_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR2_BASE, STEP_MOTOR2_PIN, GPIO_PIN_SET);
  	HAL_GPIO_WritePin(STEP_MOTOR3_BASE, STEP_MOTOR3_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR4_BASE, STEP_MOTOR4_PIN, GPIO_PIN_RESET);
  	osDelay(2);

  	HAL_GPIO_WritePin(STEP_MOTOR1_BASE, STEP_MOTOR1_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR2_BASE, STEP_MOTOR2_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR3_BASE, STEP_MOTOR3_PIN, GPIO_PIN_SET);
  	HAL_GPIO_WritePin(STEP_MOTOR4_BASE, STEP_MOTOR4_PIN, GPIO_PIN_RESET);
  	osDelay(2);

  	HAL_GPIO_WritePin(STEP_MOTOR1_BASE, STEP_MOTOR1_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR2_BASE, STEP_MOTOR2_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR3_BASE, STEP_MOTOR3_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR4_BASE, STEP_MOTOR4_PIN, GPIO_PIN_SET);
  	osDelay(2);
}
void startTurningLeft(){
  	HAL_GPIO_WritePin(STEP_MOTOR1_BASE, STEP_MOTOR1_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR2_BASE, STEP_MOTOR2_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR3_BASE, STEP_MOTOR3_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR4_BASE, STEP_MOTOR4_PIN, GPIO_PIN_SET);
  	osDelay(2);

  	HAL_GPIO_WritePin(STEP_MOTOR1_BASE, STEP_MOTOR1_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR2_BASE, STEP_MOTOR2_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR3_BASE, STEP_MOTOR3_PIN, GPIO_PIN_SET);
  	HAL_GPIO_WritePin(STEP_MOTOR4_BASE, STEP_MOTOR4_PIN, GPIO_PIN_RESET);
  	osDelay(2);

  	HAL_GPIO_WritePin(STEP_MOTOR1_BASE, STEP_MOTOR1_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR2_BASE, STEP_MOTOR2_PIN, GPIO_PIN_SET);
  	HAL_GPIO_WritePin(STEP_MOTOR3_BASE, STEP_MOTOR3_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR4_BASE, STEP_MOTOR4_PIN, GPIO_PIN_RESET);
  	osDelay(2);

  	HAL_GPIO_WritePin(STEP_MOTOR1_BASE, STEP_MOTOR1_PIN, GPIO_PIN_SET);
  	HAL_GPIO_WritePin(STEP_MOTOR2_BASE, STEP_MOTOR2_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR3_BASE, STEP_MOTOR3_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR4_BASE, STEP_MOTOR4_PIN, GPIO_PIN_RESET);
  	osDelay(2);
}

void disableStepperMotor() {
  	HAL_GPIO_WritePin(STEP_MOTOR1_BASE, STEP_MOTOR1_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR2_BASE, STEP_MOTOR2_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR3_BASE, STEP_MOTOR3_PIN, GPIO_PIN_RESET);
  	HAL_GPIO_WritePin(STEP_MOTOR4_BASE, STEP_MOTOR4_PIN, GPIO_PIN_RESET);
}
